name: account_service
description: Account service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc_dependency_service:
    path: ../dependencies_service/bloc_dependency_service
  model_dependency_service:
    path: ../dependencies_service/model_dependency_service

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  built_value_generator: ^8.0.0
  build_runner: ^1.11.5

dependency_overrides:
  analyzer: ^1.0.0