name: account_service
description: Account service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bloc_dependency_service:
    path: ../dependencies_service/bloc_dependency_service
  model_dependency_service:
    path: ../dependencies_service/model_dependency_service

dev_dependencies:
  dev_dependency_service:
    path: ../dependencies_service/dev_dependency_service