name: login_service
description: Login service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  bloc_dependency_service:
    path: ../dependencies_service/bloc_dependency_service
  authentication_service:
    path: ../authentication_service
  account_service:
    path: ../account_service
  http_service:
    path: ../http_service

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5