name: fullscreen_service
description: Fullscreen service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  convert: ^3.0.0
  bloc_dependency_service:
    path: ../dependencies_service/bloc_dependency_service
  http_service:
    path: ../http_service
  constants_service:
    path: ../constants_service
  gallery_service:
    path: ../gallery_service
  github_service:
    path: ../github_service

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
