name: gallery
description: >
  A responsive Flutter gallery application for
  any platform using micro-service architecture.
homepage: https://aliyazdi75.github.io/gallery
repository: https://github.com/aliyazdi75/gallery
issue_tracker: https://github.com/aliyazdi75/gallery/issues
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localized_locales: any
  cupertino_icons: any
  scrollable_positioned_list: ^0.1.8
  photo_view: ^0.10.3
  animations: ^1.1.2

  bloc_dependency_service:
    path: services/dependencies_service/bloc_dependency_service
  model_dependency_service:
    path: services/dependencies_service/model_dependency_service
  video_dependency_service:
    path: services/dependencies_service/video_dependency_service
  constants_service:
    path: services/constants_service
  layout_service:
    path: services/layout_service
  options_service:
    path: services/options_service
  themes_service:
    path: services/themes_service
  account_service:
    path: services/account_service
  authentication_service:
    path: services/authentication_service
  login_service:
    path: services/login_service
  gallery_service:
    path: services/gallery_service
  video_service:
    path: services/video_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: any
#  built_value_generator: ^8.0.0-nullsafety.0
  built_value_generator: any
  pedantic: ^1.10.0-nullsafety.3
  flutter_launcher_icons: any

dependency_overrides:
  built_collection: 5.0.0-nullsafety.0
  built_value: 8.0.0-nullsafety.0
  analyzer: 0.41.1
  _fe_analyzer_shared: 14.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - fonts/google_fonts/
    - assets/response.json

  fonts:
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
