name: gallery
description: A responsive Flutter gallery application for any platforms.
homepage: https://aliyazdi75.github.io
repository: https://github.com/aliyazdi75/gallery
issue_tracker: https://github.com/aliyazdi75/gallery/issues
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localized_locales: any
  cupertino_icons: any
  scrollable_positioned_list: ^0.1.8
  photo_view: ^0.10.3

  bloc_dependency_service:
    path: services/dependencies/bloc
  model_dependency_service:
    path: services/dependencies/model
  vodeo_dependency_service:
    path: services/dependencies/video
  constants_service:
    path: services/constants
  layout_service:
    path: services/layout
  options_service:
    path: services/options
  themes_service:
    path: services/themes
  routers_service:
    path: services/routers
  account_service:
    path: services/account
  authentication_service:
    path: services/authentication
  login_service:
    path: services/login
  gallery_service:
    path: services/gallery
  video_service:
    path: services/video

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: any
  built_value_generator: any
  pedantic: any
  flutter_launcher_icons: any

dependency_overrides:
  built_value: '>=7.0.0 <7.2.0'
  built_collection: ^4.3.2
  analyzer: 0.41.1
  _fe_analyzer_shared: 14.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - fonts/google_fonts/
    - assets/response.json

  fonts:
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
