name: gallery
description: >
  A responsive Flutter gallery application for
  any platform using the micro-service architecture.
homepage: https://aliyazdi75.github.io/gallery
repository: https://github.com/aliyazdi75/gallery
issue_tracker: https://github.com/aliyazdi75/gallery/issues
publish_to: none
version: 1.1.1+2

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0-nullsafety.2
  animations: ^2.0.0
  photo_view: ^0.11.0

  video_dependency_service:
    path: services/dependencies_service/video_dependency_service
  constants_service:
    path: services/constants_service
  layout_service:
    path: services/layout_service
  options_service:
    path: services/options_service
  themes_service:
    path: services/themes_service
  account_service:
    path: services/account_service
  authentication_service:
    path: services/authentication_service
  login_service:
    path: services/login_service
  gallery_service:
    path: services/gallery_service
  fullscreen_service:
    path: services/fullscreen_service
  video_service:
    path: services/video_service
  routers_service:
    path: services/routers_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
#  flutter_launcher_icons: any

#flutter_icons:
#  android: 'launcher_icon'
#  ios: true
#  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - fonts/google_fonts/
    - assets/responses/albums/album1.json
    - assets/responses/albums/album2.json
    - assets/responses/albums/album3.json
    - assets/responses/albums/album4.json
    - assets/responses/albums/album5.json
    - assets/responses/photos/photo1.json
    - assets/responses/photos/photo2.json
    - assets/responses/photos/photo3.json
    - assets/responses/photos/photo4.json
    - assets/responses/photos/photo5.json
    - assets/responses/photos/photo6.json
    - assets/responses/photos/photo7.json
    - assets/responses/photos/photo8.json
    - assets/responses/photos/photo9.json
    - assets/responses/photos/photo10.json

  fonts:
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
