name: options_service
description: Options service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  constants_service:
    path: ../constants
  themes_service:
    path: ../themes