name: login_service
description: Login service.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc_dependency_service:
    path: ../dependencies/bloc
  authentication_service:
    path: ../authentication
  account_service:
    path: ../account
  http_service:
    path: ../http